apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: memcached
spec:
  releaseName: memcached
  chart:
    spec:
      chart: memcached
      version: 7.7.1 # {"$imagepolicy": "apps-update:backend-memcached:tag"}
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
  interval: 50m
  driftDetection:
    mode: disabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/memcached?modal=values
  values:
    clusterDomain: cluster.local
