apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: 19.4.0 # {"$imagepolicy": "apps-update:backend-redis:tag"}
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
  interval: 50m
  driftDetection:
    mode: disabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/redis?modal=values
  values:
    master:
      kind: StatefulSet
      persistence:
        enabled: false
    replica:
      kind: StatefulSet
      replicaCount: 1
      persistence:
        enabled: false
