apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: 24.1.2 # {"$imagepolicy": "apps-update:backend-redis:tag"}
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
  interval: 50m
  driftDetection:
    mode: disabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/redis?modal=values
  values:
    master:
      kind: StatefulSet
      persistence:
        enabled: false
    replica:
      kind: StatefulSet
      replicaCount: 1
      persistence:
        enabled: false
    global:
      security:
        allowInsecureImages: true
    image:
      repository: bitnamilegacy/redis
    sentinel:
      image:
        repository: bitnamilegacy/redis-sentinel
    metrics:
      image:
        repository: bitnamilegacy/redis-exporter
    kubectl:
      image:
        repository: bitnamilegacy/kubectl
    volumePermissions:
      image:
        repository: bitnamilegacy/os-shell
    sysctl:
      image:
        repository: bitnamilegacy/os-shell
