apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: 18.13.10
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
  interval: 50m
  driftDetection:
    mode: disabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://artifacthub.io/packages/helm/bitnami/redis?modal=values
  values:
    master:
      kind: Deployment
      persistence:
        enabled: false
    replica:
      kind: Deployment
      replicaCount: 1
      persistence:
        enabled: false
