apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/stefanprodan/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: 6.7.1 # {"$imagepolicy": "apps-update:frontend-podinfo:tag"}
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 50m
  driftDetection:
    mode: enabled
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: podinfo.${CLUSTER_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
